import type { IdentityTemplateConfig, IdentityTemplate } from '@/types'

export const IDENTITY_TEMPLATES: Record<IdentityTemplate, IdentityTemplateConfig> = {
  disciplined: {
    label: 'Disciplined Creator',
    description: 'Someone who shows up every day, no matter what',
    color: '#4F46E5',
    icon: '⚡',
    affirmation: 'You are becoming someone who keeps their word to themselves.',
    suggestedHabits: [
      'Write for 5 minutes daily',
      'Wake up at the same time',
      'Complete one deep work session',
      'Plan tomorrow the night before',
    ],
  },
  healthy: {
    label: 'Healthy Human',
    description: 'Someone who treats their body as their most important asset',
    color: '#10B981',
    icon: '🌿',
    affirmation: 'You are becoming someone who honors their body.',
    suggestedHabits: [
      'Drink 8 glasses of water',
      'Walk 10 minutes after meals',
      'Sleep by 10:30pm',
      'Eat one serving of vegetables',
    ],
  },
  focused: {
    label: 'Deep Worker',
    description: 'Someone who can do their best work without distraction',
    color: '#F59E0B',
    icon: '🎯',
    affirmation: 'You are becoming someone who does deep, meaningful work.',
    suggestedHabits: [
      '90 minutes of focused work',
      'Phone-free morning hour',
      'Single-task one project',
      'Daily review and planning',
    ],
  },
  calm: {
    label: 'Calm Mind',
    description: 'Someone who responds thoughtfully rather than reacting impulsively',
    color: '#06B6D4',
    icon: '🌊',
    affirmation: 'You are becoming someone who chooses peace.',
    suggestedHabits: [
      'Meditate for 5 minutes',
      'Take 3 deep breaths before responding',
      'Evening screen-free wind-down',
      'Gratitude journaling',
    ],
  },
  athletic: {
    label: 'Athlete',
    description: 'Someone who pushes their physical limits consistently',
    color: '#EF4444',
    icon: '💪',
    affirmation: 'You are becoming someone who is physically capable.',
    suggestedHabits: [
      'Move for 20 minutes',
      'Stretch for 5 minutes after waking',
      'Track daily steps',
      'Prepare workout clothes the night before',
    ],
  },
  productive: {
    label: 'High Performer',
    description: 'Someone who gets important things done first',
    color: '#8B5CF6',
    icon: '🚀',
    affirmation: 'You are becoming someone who makes things happen.',
    suggestedHabits: [
      'Identify 3 MIT (Most Important Tasks)',
      'Work in 25-minute Pomodoro blocks',
      'Weekly review every Sunday',
      'Zero inbox once a day',
    ],
  },
  creative: {
    label: 'Creative',
    description: 'Someone who expresses and creates something new each day',
    color: '#EC4899',
    icon: '🎨',
    affirmation: 'You are becoming someone who creates rather than consumes.',
    suggestedHabits: [
      'Create something for 10 minutes',
      'Fill one page in a sketchbook',
      'Practice your craft',
      'Curate one piece of inspiration',
    ],
  },
  mindful: {
    label: 'Mindful Soul',
    description: 'Someone who lives with intention and awareness',
    color: '#14B8A6',
    icon: '🧘',
    affirmation: 'You are becoming someone who lives with full presence.',
    suggestedHabits: [
      'Morning meditation (5 min)',
      'Mindful eating at one meal',
      'Evening reflection journal',
      'Single-tasking practice',
    ],
  },
  reader: {
    label: 'Lifelong Reader',
    description: 'Someone who feeds their mind with knowledge daily',
    color: '#6366F1',
    icon: '📚',
    affirmation: 'You are becoming someone who grows through reading.',
    suggestedHabits: [
      'Read 10 pages daily',
      'Highlight and take notes',
      'Share one insight weekly',
      'Read before bed instead of scrolling',
    ],
  },
  entrepreneur: {
    label: 'Builder',
    description: 'Someone who builds things that matter',
    color: '#F97316',
    icon: '🏗️',
    affirmation: 'You are becoming someone who creates value.',
    suggestedHabits: [
      'Work on your project for 30 minutes',
      'Talk to one customer or user',
      'Learn one new business skill',
      'Review your goals weekly',
    ],
  },
  learner: {
    label: 'Curious Learner',
    description: 'Someone who is always growing and learning',
    color: '#0EA5E9',
    icon: '🧠',
    affirmation: 'You are becoming someone who never stops growing.',
    suggestedHabits: [
      'Learn something new for 15 minutes',
      'Practice a skill deliberately',
      'Teach what you learned',
      'Ask one curious question daily',
    ],
  },
  minimalist: {
    label: 'Minimalist',
    description: 'Someone who finds freedom in less',
    color: '#94A3B8',
    icon: '✦',
    affirmation: 'You are becoming someone who values quality over quantity.',
    suggestedHabits: [
      'Remove one unused item',
      'One-in-one-out rule',
      'Digital declutter for 5 minutes',
      'Intentional purchasing pause',
    ],
  },
}

export const HABIT_CATEGORIES = [
  { id: 'health', label: 'Health', icon: '❤️', color: '#10B981' },
  { id: 'fitness', label: 'Fitness', icon: '💪', color: '#EF4444' },
  { id: 'mindfulness', label: 'Mindfulness', icon: '🧘', color: '#14B8A6' },
  { id: 'learning', label: 'Learning', icon: '📚', color: '#6366F1' },
  { id: 'creativity', label: 'Creativity', icon: '🎨', color: '#EC4899' },
  { id: 'relationships', label: 'Relationships', icon: '👥', color: '#F59E0B' },
  { id: 'finances', label: 'Finances', icon: '💰', color: '#10B981' },
  { id: 'productivity', label: 'Productivity', icon: '⚡', color: '#8B5CF6' },
  { id: 'spirituality', label: 'Spirituality', icon: '✨', color: '#F97316' },
  { id: 'other', label: 'Other', icon: '🌟', color: '#94A3B8' },
] as const
